Fix contenerization

diff --git a/docker/php-fpm/Dockerfile b/docker/php-fpm/Dockerfile
--- a/docker/php-fpm/Dockerfile
+++ b/docker/php-fpm/Dockerfile
@@ -2,25 +2,69 @@ FROM php:8.1-fpm
 
 COPY --from=composer /usr/bin/composer /usr/bin/composer
 
+# Set Environment Variables
+ENV DEBIAN_FRONTEND noninteractive
+
+RUN set -eux; \
+    apt-get update; \
+    apt-get upgrade -y; \
+    apt-get install -yqq apt-utils; \
+    apt-get install -y --no-install-recommends \
+            curl \
+            libmemcached-dev \
+            libz-dev \
+            libpq-dev \
+            libjpeg-dev \
+            libpng-dev \
+            libfreetype6-dev \
+            libssl-dev \
+            libmcrypt-dev \
+            libonig-dev \
+            libzip-dev zip unzip;
+
+RUN set -eux; \
+    docker-php-ext-configure gd \
+            --prefix=/usr \
+            --with-jpeg \
+            --with-freetype; \
+    docker-php-ext-install gd; \
+    docker-php-ext-configure zip; \
+    docker-php-ext-install zip; \
+    docker-php-ext-install bcmath; \
+    php -r 'var_dump(gd_info());'
+
+
+RUN set -xe; \
+    pecl channel-update pecl.php.net
+
+COPY ./php.ini /usr/local/etc/php/php.ini
+
+USER root
+
+# Clean up
+RUN apt-get clean && \
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
+    rm /var/log/lastlog /var/log/faillog
+
+# Configure non-root user.
+ARG PUID=1000
+ENV PUID ${PUID}
+ARG PGID=1000
+ENV PGID ${PGID}
+
+RUN groupmod -o -g ${PGID} www-data && \
+    usermod -o -u ${PUID} -g www-data www-data
+
+# Configure locale.
+ARG LOCALE=POSIX
+ENV LC_ALL ${LOCALE}
+
 WORKDIR /var/www
 
-RUN \
-    apt-get update \
-    && apt-get install -y \
-        curl \
-        libpng-dev \
-        libonig-dev \
-        libxml2-dev \
-        librabbitmq-dev \
-        zip \
-        unzip \
-        git \
-    && apt-get clean \
-    && rm -rf /var/lib/apt/lists/* \
-    && pecl install amqp \
-    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd intl \
-    && docker-php-ext-enable amqp \
-    && mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" \
-    && sed -i 's#;date\.timezone =#date\.timezone = Europe/Warsaw#' "$PHP_INI_DIR/php.ini"
+CMD ["php-fpm"]
 
-USER www-data
+EXPOSE 9000
+
+
+
+
